In [33]:
check_df = pd.read_csv("applicants_cleaned.csv")

print("Saved CSV shape:", check_df.shape)
print("Duplicate rows:", check_df.duplicated().sum())
print("\nMissing values:")
print(check_df.isnull().sum())

Saved CSV shape: (98, 5)
Duplicate rows: 0

Missing values:
Applicant_ID    0
Name            0
Email           3
Age             2
City            0
dtype: int64

In [32]:
from google.colab import files

files.download("applicants_cleaned.csv")

# **Data Quality Summary**

## Starting Dataset

The original dataset contained 100 rows and 5 columns: `Applicant_ID`, `Name`, `Email`, `Age`, and `City`.

## Issues Found

- 6 missing values in the Email column.
- 2 missing values in the Age column.
- 2 exact duplicate rows.
- Three invalid email formats: `invalid-email`, `abc@`, and `user@@gmail.com`.
- Inconsistent capitalization and whitespace in some city names, such as `islamabad` and `LAHORE`.
- Invalid or potentially unrealistic age values, including `-5` and `150`.
- A non-numeric age value, `twenty-five`.

## Actions Taken

- Filled the initially missing Email values with `not_provided@example.com` to retain applicant records.
- Replaced `twenty-five` with `25` and converted the Age column to a numeric data type.
- Filled the initially missing Age values using the median.
- Removed 2 exact duplicate rows using `drop_duplicates()`.
- Removed leading and trailing whitespace from the Name, Email, and City columns.
- Standardized Name and City capitalization using title case and converted email addresses to lowercase.
- Checked for duplicate email addresses, excluding the placeholder email from the check.
- Used regular expressions to identify invalid email formats and replaced the three invalid email values with `NaN`.
- Identified unrealistic age values and replaced invalid ages with `NaN`.
- Verified the final dataset structure, missing values, and data types using `df.info()` and `df.isnull().sum()`.

## Final Dataset

The final dataset contains **98 rows and 5 columns**. The latest validation shows 3 missing values in the Email column and 2 missing values in the Age column. The `Applicant_ID`, `Name`, and `City` columns have no missing values.

The data types are `int64` for `Applicant_ID`, `float64` for `Age`, and `object` for `Name`, `Email`, and `City`.

## Conclusion

The cleaning process improved text consistency, removed exact duplicate rows, standardized data types, and identified invalid email formats and unrealistic ages. Invalid email and age values were replaced with missing values rather than deleting entire applicant records. The remaining missing values have been documented and should be verified or handled appropriately before further analysis. The cleaned dataset was exported as `applicants_cleaned.csv` for submission.

In [27]:
print("Final dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nExact duplicate rows:", df.duplicated().sum())

Final dataset shape: (98, 5)

Missing values:
Applicant_ID    0
Name            0
Email           3
Age             2
City            0
dtype: int64

Exact duplicate rows: 0

In [26]:
print("Final dataset shape:", df.shape)
print(df.isnull().sum())

Final dataset shape: (98, 5)
Applicant_ID    0
Name            0
Email           3
Age             2
City            0
dtype: int64

In [25]:
print("Final dataset shape:", df.shape)
print("Saved file exists:", os.path.exists('applicants_cleaned.csv'))

Final dataset shape: (98, 5)
Saved file exists: True

In [24]:
import os

print(os.path.exists('applicants_cleaned.csv'))

True

In [23]:
df.to_csv('applicants_cleaned.csv', index=False)

In [22]:
print("Final dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
df.info()

Final dataset shape: (98, 5)

Missing values:
Applicant_ID    0
Name            0
Email           3
Age             2
City            0
dtype: int64

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  98 non-null     int64
 1   Name          98 non-null     object
 2   Email         95 non-null     object
 3   Age           96 non-null     float64
 4   City          98 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  98 non-null     int64
 1   Name          98 non-null     object
 2   Email         95 non-null     object
 3   Age           96 non-null     float64
 4   City          98 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

### Handling Invalid Email Addresses

Regular expressions were used to validate email formats. Three invalid email addresses were identified: `invalid-email`, `abc@`, and `user@@gmail.com`. These values were replaced with `NaN` to mark them as missing or invalid. The applicants' records were retained to avoid losing other useful information.

A valid email format does not guarantee that the email account exists or is active. For example, `user@example.com` has a valid format, but its existence cannot be confirmed through regular expressions alone.

### Handling Unrealistic Age Values

The Age column was converted to numeric format, and unrealistic values below 0 or above 100 were identified as invalid. These values were replaced with `NaN` rather than deleting the applicants' records. This prevents invalid ages from affecting further analysis.

The correct ages should be verified using the original records or by contacting the applicants before replacing the missing values with confirmed information.

In [20]:
print("Missing ages:", df["Age"].isna().sum())

print("\nRemaining invalid ages:")
print(df.loc[
    (df["Age"] < 0) | (df["Age"] > 100),
    ["Applicant_ID", "Name", "Age"]
])

Missing ages: 2

Remaining invalid ages:
Empty DataFrame
Columns: [Applicant_ID, Name, Age]
Index: []

In [19]:
# Check the records whose ages were invalid
print(df.loc[
    df["Age"].isna(),
    ["Applicant_ID", "Name", "Age"]
])

    Applicant_ID             Name  Age
14            15  Micheal Pearson  NaN
27            29  Mr. Paul Burton  NaN

In [18]:
# Replace invalid ages with NaN
df.loc[invalid_age_mask, "Age"] = float("nan")

In [17]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

invalid_age_mask = (df["Age"] < 18) | (df["Age"] > 100)

print("Invalid age records:")
print(df.loc[
    invalid_age_mask,
    ["Applicant_ID", "Name", "Age"]
])

Invalid age records:
Empty DataFrame
Columns: [Applicant_ID, Name, Age]
Index: []

In [16]:
df.loc[invalid_mask, "Email"] = float("nan")

Invalid email records:
    Applicant_ID             Name            Email
12            13  William Sherman    invalid-email
29            31    Gina Young Md             abc@
43            46  Sharon Morrison  user@@gmail.com

In [7]:
import pandas as pd

df = pd.read_csv("applicants_cleaned.csv")

print(df.shape)
print(df.head())

(98, 5)
   Applicant_ID                Name                       Email  Age  \
0             1         Jack Harris    torresbrandy@example.com   39
1             2        Sarah Morris  smithcassandra@example.net   24
2             3       Kevin Goodwin    not_provided@example.com   37
3             4  Kenneth Johnson Ii        regina08@example.com   28
4             5   Stephanie Robbins         cathy95@example.com   34

               City
0          Kyleport
1       Goodwinside
2  Lake Danielville
3       North Nancy
4         Islamabad

In [ ]:
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

invalid_mask = (
    df["Email"].notna()
    & (df["Email"] != "not_provided@example.com")
    & ~df["Email"].str.match(email_pattern, na=False)
)

df.loc[invalid_mask, ["Applicant_ID", "Name", "Email"]]

    Applicant_ID             Name            Email
12            13  William Sherman    invalid-email
30            31    Gina Young Md             abc@
45            46  Sharon Morrison  user@@gmail.com

In [ ]:
df.loc[
    df["Applicant_ID"].isin([13, 31, 46, 34]),
    ["Applicant_ID", "Name", "Email"]
]

    Applicant_ID             Name            Email
12            13  William Sherman    invalid-email
30            31    Gina Young Md             abc@
33            34     Michelle Lee  ali@example.com
45            46  Sharon Morrison  user@@gmail.com

### **Fix Data Types**
 I verified the data types using `df.info()`, which confirmed that Age is stored as `float64` and Applicant_ID is stored as `int64`. The Name, Email, and City columns are stored as object (text) types.

The dataset contains 98 rows and 5 columns. The Application Date and Phone columns are not present in this dataset, so date conversion and phone number cleaning were not applicable.

This step ensures that the Age column can be used for numerical analysis and calculations.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  98 non-null     int64
 1   Name          98 non-null     object
 2   Email         98 non-null     object
 3   Age           98 non-null     float64
 4   City          98 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.6+ KB

### **Standardize Text Fields**

I standardized the text fields by removing leading and trailing whitespace and applying consistent capitalization. Names and city names were converted to title case, while email addresses were converted to lowercase.

I checked the unique values in the City and Email columns to verify the changes. The city names are displayed consistently, and the email addresses use lowercase formatting. However, some email addresses still have invalid formats, which will require separate validation.

This step helps ensure consistent text values for accurate grouping, matching, and analysis.

In [ ]:
print(df["Name"].str.contains(r"^\s|\s$", na=False).sum())
print(df["Email"].str.contains(r"^\s|\s$", na=False).sum())
print(df["City"].str.contains(r"^\s|\s$", na=False).sum())

0
0
0

In [ ]:
print(df["City"].unique())
print(df["Email"].unique())

['Kyleport' 'Goodwinside' 'Lake Danielville' 'North Nancy' 'Islamabad'
 'East Claytonside' 'West Mallorybury' 'North Adamland' 'Gordonfurt'
 'Lake Krista' 'East Dannyview' 'Vasquezland' 'Stricklandport'
 'Thomasview' 'East Joe' 'Lake Abigailmouth' 'Port Joanne'
 'East Jonathanstad' 'Nicolemouth' 'South Sandraland' 'Robinfurt'
 'New Christopherborough' 'Josephville' 'Kelleyshire' 'Lahore'
 'East Dianahaven' 'Elizabethstad' 'Laurenhaven' 'West Wendyfort'
 'Edwardsfort' 'Lake Jessicamouth' 'West Ashley' 'Nicholshaven'
 'Johnsonchester' 'Wrightside' 'North Larryfurt' 'North Ronaldburgh'
 'Johnsonmouth' 'Lake Emily' 'East Sheryl' 'New Catherineborough'
 'Josephmouth' 'Racheltown' 'South Thomas' 'Murrayland' 'Maddenville'
 'Port Mirandaton' 'New Christopherton' 'Rhondashire' 'Johnmouth'
 'West Daniel' 'Lopezside' 'Port Lindaberg' 'East Robertchester'
 'West Lisafort' 'New Christopher' 'West Jenna' 'Aliciaburgh' 'Murphytown'
 'Briannaside' 'West Amandaton' 'Walshshire' 'Blackland' 'Bruceshire'
 'Wallacebury' 'Pamelatown' 'Mooreside' 'Taylorstad' 'Lake Colin'
 'Lake Tammyfurt' 'East Evelynville' 'Christopherstad' 'Mackenzieport'
 'New Michael' 'Arellanoside' 'North Michaelside' 'Lake Kevinmouth'
 'Karenmouth' 'East Kristin' 'North Jennifer' 'Campbellburgh'
 'Gregoryside' 'Durhamburgh' 'New James' 'Caldwellshire' 'East Raymond'
 'Riceview' 'Duncanchester' 'North Taylorhaven' 'Garyhaven' 'Harperfurt'
 'Richardton' 'Karenview' 'Smithport' 'North David' 'Nelsonberg'
 'Perezmouth' 'East Katherinehaven']
['torresbrandy@example.com' 'smithcassandra@example.net'
 'not_provided@example.com' 'regina08@example.com' 'cathy95@example.com'
 'solisamy@example.com' 'ibrown@example.org' 'nicole00@example.org'
 'michaelarivera@example.org' 'gharrison@example.org'
 'roberthughes@example.com' 'invalid-email' 'sandra47@example.net'
 'rgrant@example.net' 'sheila99@example.org' 'mmartinez@example.org'
 'franciscoferrell@example.com' 'hhowe@example.com'
 'ronaldtucker@example.com' 'umoore@example.com'
 'fletcherdarryl@example.com' 'rachel01@example.net'
 'michaelmorrison@example.net' 'andreaalexander@example.com'
 'ulozano@example.com' 'khughes@example.com' 'abc@' 'kjohnson@example.org'
 'baileyhannah@example.org' 'ali@example.com' 'dhudson@example.net'
 'pprice@example.com' 'deborah31@example.org' 'caleb59@example.com'
 'michaelhartman@example.org' 'paul82@example.net' 'jay16@example.org'
 'xmendoza@example.org' 'rachel45@example.net' 'user@@gmail.com'
 'pgreene@example.com' 'wjohnson@example.org' 'jeremybailey@example.org'
 'anna79@example.org' 'ujones@example.net' 'susan60@example.net'
 'brandonadkins@example.com' 'zcarney@example.org' 'boconnor@example.org'
 'lopezmolly@example.net' 'juliegrant@example.net'
 'malloryherrera@example.net' 'htrevino@example.com'
 'cynthia83@example.com' 'ehernandez@example.com' 'fhammond@example.org'
 'michaelcordova@example.org' 'williamspatricia@example.net'
 'carlsontyler@example.com' 'barrettsarah@example.net'
 'cowens@example.com' 'xdickerson@example.org' 'mary51@example.com'
 'qjohnston@example.net' 'leestacey@example.com'
 'francodaniel@example.net' 'andreperry@example.net' 'owade@example.com'
 'jacqueline50@example.com' 'sfuller@example.com'
 'melendezemily@example.com' 'robert09@example.net'
 'elizabeth54@example.net' 'kenneth36@example.com'
 'jennifercortez@example.com' 'jrich@example.net' 'cheryl32@example.net'
 'beckermonica@example.org' 'molly05@example.com'
 'johnferguson@example.net' 'jessicafleming@example.net'
 'pollardcarol@example.com' 'david57@example.com' 'jcole@example.org'
 'stephensmith@example.com' 'hbrown@example.org' 'truiz@example.org'
 'joneslaurie@example.org' 'pwilliams@example.com'
 'stephanie73@example.org' 'hughesemma@example.net'
 'crystalmyers@example.net' 'jobrown@example.org']

In [ ]:
df["Name"] = df["Name"].str.title()
df["Email"] = df["Email"].str.lower()
df["City"] = df["City"].str.title()

In [ ]:
df["Name"] = df["Name"].str.strip()
df["Email"] = df["Email"].str.strip()
df["City"] = df["City"].str.strip()

In [ ]:
df.columns

Index(['Applicant_ID', 'Name', 'Email', 'Age', 'City'], dtype='object')

### **Duplicate Applicant Removal**

I first checked for exact duplicate rows and removed repeated records using `drop_duplicates()`. The dataset initially contained 100 rows, including 2 exact duplicate rows. After removing them, 98 rows remained.

I then checked for duplicate applicants using standardized email addresses. No duplicate real email addresses were found. I excluded the placeholder email (`not_provided@example.com`) from this check because it represents missing email information and does not uniquely identify an applicant.

Therefore, no additional rows were removed based on email duplicates. The final dataset contains **98 rows and 5 columns**.

In [ ]:
mask = df["Email"] != "not_provided@example.com"

df.loc[mask & df["Email"].duplicated(keep=False)].sort_values("Email")

Empty DataFrame
Columns: [Applicant_ID, Name, Email, Age, City]
Index: []

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

Now,I'll remove the duplicate aplicants.

In [ ]:
df["Age"].isnull().sum()

np.int64(0)

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [ ]:
df["Email"].isnull().sum()

np.int64(0)

In [ ]:
df["Email"] = df["Email"].fillna("not_provided@example.com")

### **Missing Values Handling — Decisions and Justification**
We'll handle the missing values in  data column by column.

- **Applicant_ID:** No missing values were found,so no chabges are needed.
- **Name:** No missing values were found. Applicant names are important for identifying applicants, so rows with missing names would require careful consideration.
- **Email:** The Email column contained 6 missing values. I will fill missing email values with `not_provided@example.com` to preserve applicant records for other analyses. These placeholders must not be used for actual email outreach.
- **Age:** The Age column contained 2 missing values. I will use the median age to fill missing entries because the median is less sensitive to extreme values than the mean.
- **City:** No missing values were found, so no changes are needed.

These decisions preserve useful records while addressing missing information according to each column's purpose.

In [ ]:
df["Age"].dtype

dtype('float64')

In [ ]:
df[df["Age"] >100]

    Applicant_ID             Name                Email    Age         City
28            29  Mr. Paul Burton  ulozano@example.com  150.0  Laurenhaven

In [ ]:
df[df["Age"] < 0]

    Applicant_ID             Name               Email  Age      City
14            15  Micheal Pearson  rgrant@example.net -5.0  East Joe

In [ ]:
df["Age"] = df["Age"].replace("twenty-five", "25")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [ ]:
print(df["City"].unique())

['Kyleport' 'Goodwinside' 'Lake Danielville' 'North Nancy' ' islamabad '
 'East Claytonside' 'West Mallorybury' 'North Adamland' 'Gordonfurt'
 'Lake Krista' 'East Dannyview' 'Vasquezland' 'Stricklandport'
 'Thomasview' 'East Joe' 'Lake Abigailmouth' 'Port Joanne'
 'East Jonathanstad' 'Nicolemouth' 'South Sandraland' 'Robinfurt'
 'New Christopherborough' 'Josephville' 'Kelleyshire' 'LAHORE'
 'East Dianahaven' 'Elizabethstad' 'Laurenhaven' 'West Wendyfort'
 'Edwardsfort' 'Lake Jessicamouth' 'West Ashley' 'Nicholshaven'
 'Johnsonchester' 'Wrightside' 'North Larryfurt' 'North Ronaldburgh'
 'Johnsonmouth' 'Lake Emily' 'East Sheryl' 'New Catherineborough'
 'Josephmouth' 'Racheltown' 'South Thomas' 'Murrayland' 'Maddenville'
 'Port Mirandaton' 'New Christopherton' 'Rhondashire' 'Johnmouth'
 'West Daniel' 'Lopezside' 'Port Lindaberg' 'East Robertchester'
 'West Lisafort' 'New Christopher' 'West Jenna' 'Aliciaburgh' 'Murphytown'
 'Briannaside' 'West Amandaton' 'Walshshire' 'Blackland' 'Bruceshire'
 'Wallacebury' 'Pamelatown' 'Mooreside' 'Taylorstad' 'Lake Colin'
 'Lake Tammyfurt' 'East Evelynville' 'Christopherstad' 'Mackenzieport'
 'New Michael' 'Arellanoside' 'North Michaelside' 'Lake Kevinmouth'
 'Karenmouth' 'East Kristin' 'North Jennifer' 'Campbellburgh'
 'Gregoryside' 'Durhamburgh' 'New James' 'Caldwellshire' 'East Raymond'
 'Riceview' 'Duncanchester' 'North Taylorhaven' 'Garyhaven' 'Harperfurt'
 'Richardton' 'Karenview' 'Smithport' 'North David' 'Nelsonberg'
 'Perezmouth' 'East Katherinehaven']

In [ ]:
df[df["Email"].notna() &
   ~df["Email"].str.fullmatch(
       r"[^@\s]+@[^@\s]+\.[^@\s]+", na=False
   )]

    Applicant_ID             Name              Email   Age            City
12            13  William Sherman      invalid-email  33.0  Stricklandport
30            31    Gina Young MD               abc@  30.0     Edwardsfort
33            34     Michelle Lee   ali@example.com   33.0    Nicholshaven
45            46  Sharon Morrison    user@@gmail.com  26.0    South Thomas

In [ ]:
print(df["Age"].unique())

['39.0' '24.0' '37.0' '28.0' '34.0' '36.0' '25.0' nan '35.0' '33.0' '-5.0'
 '23.0' '32.0' '30.0' '150.0' '29.0' '40.0' '22.0' 'twenty-five' '26.0'
 '27.0' '31.0' '20.0' '38.0' '21.0']

### **Data Quality Summary** — Before Cleaning

- The dataset contains 100 rows and 5 columns.
- The Email column has 6 missing values.
- The Age column has 2 missing values.
- There are 2 exact duplicate rows, involving Jack Harris (Applicant_ID 1) and Sonya Brady (Applicant_ID 11).
- The Age column has an `object` data type instead of a purely numeric type.
- Some email addresses are invalid, and some age values are incorrect or inconsistent.
- City names have inconsistent capitalization.

These data quality issues need to be investigated and addressed before analysis.

In [ ]:
df[df.duplicated(keep=False)]

    Applicant_ID         Name                     Email   Age            City
0              1  Jack Harris  torresbrandy@example.com  39.0        Kyleport
10            11  Sonya Brady     gharrison@example.org   NaN  East Dannyview
15             1  Jack Harris  torresbrandy@example.com  39.0        Kyleport
40            11  Sonya Brady     gharrison@example.org   NaN  East Dannyview

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.isnull().sum()

Applicant_ID    0
Name            0
Email           6
Age             2
City            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  100 non-null    int64
 1   Name          100 non-null    object
 2   Email         94 non-null     object
 3   Age           98 non-null     object
 4   City          100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

In [ ]:
print(df.to_string())

    Applicant_ID                  Name                         Email          Age                    City
0              1           Jack Harris      torresbrandy@example.com         39.0                Kyleport
1              2          Sarah Morris    smithcassandra@example.net         24.0             Goodwinside
2              3         Kevin Goodwin                           NaN         37.0        Lake Danielville
3              4    Kenneth Johnson II          regina08@example.com         28.0             North Nancy
4              5     Stephanie Robbins           cathy95@example.com         34.0              islamabad
5              6      Jennifer Pacheco          solisamy@example.com         36.0        East Claytonside
6              7        Carrie Johnson            ibrown@example.org         24.0        West Mallorybury
7              8            Juan Burke                           NaN         39.0          North Adamland
8              9        Sarah Phillips          nicole00@example.org         37.0              Gordonfurt
9             10        Ayesha Malik      michaelarivera@example.org         25.0             Lake Krista
10            11           Sonya Brady         gharrison@example.org          NaN          East Dannyview
11            12        Matthew Ingram      roberthughes@example.com         35.0             Vasquezland
12            13       William Sherman                 invalid-email         33.0          Stricklandport
13            14         Cynthia Lucas          sandra47@example.net         35.0              Thomasview
14            15       Micheal Pearson            rgrant@example.net         -5.0                East Joe
15             1           Jack Harris      torresbrandy@example.com         39.0                Kyleport
16            17          Jessica Hunt          sheila99@example.org         25.0       Lake Abigailmouth
17            18      Jessica Sullivan         mmartinez@example.org         35.0             Port Joanne
18            19    Elizabeth Thompson                           NaN         28.0       East Jonathanstad
19            20            Amy Wright  franciscoferrell@example.com         25.0             Nicolemouth
20            21         George Abbott             hhowe@example.com         23.0        South Sandraland
21            22          Ashley Weiss      ronaldtucker@example.com         32.0               Robinfurt
22            23      Cassandra Nelson            umoore@example.com         32.0  New Christopherborough
23            24            Ryan James    fletcherdarryl@example.com         39.0             Josephville
24            25         Eduardo Perez                           NaN         39.0             Kelleyshire
25            26         Nicholas Rush          rachel01@example.net         34.0                  LAHORE
26            27      Anthony Williams   michaelmorrison@example.net         36.0         East Dianahaven
27            28     Donald Guerra DDS   andreaalexander@example.com         30.0           Elizabethstad
28            29       Mr. Paul Burton           ulozano@example.com        150.0             Laurenhaven
29            30         Willie Foster           khughes@example.com         33.0          West Wendyfort
30            31         Gina Young MD                          abc@         30.0             Edwardsfort
31            32       Robert Atkinson          kjohnson@example.org         29.0       Lake Jessicamouth
32            33           Max Gardner      baileyhannah@example.org         40.0             West Ashley
33            34          Michelle Lee              ali@example.com          33.0            Nicholshaven
34            35    Mrs. Laurie Juarez           dhudson@example.net         22.0          Johnsonchester
35            36          Evan Mcmahon            pprice@example.com         28.0              Wrightside
36            37        Sarah Faulkner                           NaN         30.0         North Larryfurt
37            38           Dustin Rose         deborah31@example.org         37.0       North Ronaldburgh
38            39     Nicholas Williams           caleb59@example.com         28.0            Johnsonmouth
39            40         Elaine Rogers    michaelhartman@example.org  twenty-five              Lake Emily
40            11           Sonya Brady         gharrison@example.org          NaN          East Dannyview
41            42      Richard Caldwell            paul82@example.net         25.0             East Sheryl
42            43          Robert Scott             jay16@example.org         26.0    New Catherineborough
43            44          Brooke White          xmendoza@example.org         35.0             Josephmouth
44            45        Marie Griffith          rachel45@example.net         22.0              Racheltown
45            46       Sharon Morrison               user@@gmail.com         26.0            South Thomas
46            47     Matthew Gutierrez           pgreene@example.com         26.0              Murrayland
47            48           Carol Fritz          wjohnson@example.org         37.0             Maddenville
48            49   Christopher Harding                           NaN         36.0         Port Mirandaton
49            50        Laura Cummings      jeremybailey@example.org         32.0      New Christopherton
50            51     Mr. Randall Evans            anna79@example.org         29.0             Rhondashire
51            52           Tony Acosta            ujones@example.net         34.0               Johnmouth
52            53           Edwin Brown           susan60@example.net         35.0             West Daniel
53            54          Joshua Bowen     brandonadkins@example.com         32.0               Lopezside
54            55          Brianna Kerr           zcarney@example.org         24.0          Port Lindaberg
55            56       Catherine Brown          boconnor@example.org         27.0      East Robertchester
56            57           Rachel Bell        lopezmolly@example.net         32.0           West Lisafort
57            58         Mindy Cabrera        juliegrant@example.net         35.0         New Christopher
58            59          Robert Ramos    malloryherrera@example.net         31.0              West Jenna
59            60          Javier Patel          htrevino@example.com         28.0             Aliciaburgh
60            61         Katrina Yoder         cynthia83@example.com         32.0              Murphytown
61            62       Alexandra Smith        ehernandez@example.com         29.0             Briannaside
62            63         Sarah Gardner          fhammond@example.org         20.0          West Amandaton
63            64         Louis Marquez    michaelcordova@example.org         25.0              Walshshire
64            65         Rebecca Sloan  williamspatricia@example.net         26.0               Blackland
65            66           Nicole Kirk      carlsontyler@example.com         29.0              Bruceshire
66            67           Amber Welch      barrettsarah@example.net         26.0             Wallacebury
67            68            Tammy Ball            cowens@example.com         37.0              Pamelatown
68            69         Ashlee Taylor        xdickerson@example.org         20.0               Mooreside
69            70           Ann Hartman            mary51@example.com         36.0              Taylorstad
70            71       Andrew Stafford         qjohnston@example.net         40.0              Lake Colin
71            72          Craig Morris         leestacey@example.com         22.0          Lake Tammyfurt
72            73          Jacob Harper      francodaniel@example.net         38.0        East Evelynville
73            74           Jerome Park        andreperry@example.net         30.0         Christopherstad
74            75            Sarah Sims             owade@example.com         20.0           Mackenzieport
75            76        Bradley Farley      jacqueline50@example.com         27.0             New Michael
76            77       Rodney Martinez           sfuller@example.com         26.0            Arellanoside
77            78         Angela Thomas     melendezemily@example.com         35.0       North Michaelside
78            79           Chad Howard          robert09@example.net         25.0         Lake Kevinmouth
79            80          Caleb Dillon       elizabeth54@example.net         23.0              Karenmouth
80            81           Mary Thomas         kenneth36@example.com         35.0            East Kristin
81            82       Benjamin Austin    jennifercortez@example.com         28.0          North Jennifer
82            83          Anthony Wall             jrich@example.net         27.0           Campbellburgh
83            84        Benjamin Brown          cheryl32@example.net         37.0             Gregoryside
84            85        Stephen Austin      beckermonica@example.org         29.0             Durhamburgh
85            86           David Glenn           molly05@example.com         38.0               New James
86            87           Lisa Hunter      johnferguson@example.net         35.0           Caldwellshire
87            88      Maurice Williams    jessicafleming@example.net         29.0            East Raymond
88            89   Adriana Wallace PhD      pollardcarol@example.com         28.0                Riceview
89            90  Mrs. Kristin Wheeler           david57@example.com         31.0           Duncanchester
90            91        April Mcmillan             jcole@example.org         27.0       North Taylorhaven
91            92          Vickie Adams      stephensmith@example.com         27.0               Garyhaven
92            93           Jason Mayer            hbrown@example.org         29.0              Harperfurt
93            94         Cynthia Jones             truiz@example.org         32.0              Richardton
94            95          Donna Newman       joneslaurie@example.org         29.0               Karenview
95            96         Richard Welch         pwilliams@example.com         34.0               Smithport
96            97            Derek Wong       stephanie73@example.org         35.0             North David
97            98     Mr. Robert Massey        hughesemma@example.net         27.0              Nelsonberg
98            99         Ashley Dudley      crystalmyers@example.net         37.0              Perezmouth
99           100        Brittany Mayer           jobrown@example.org         21.0     East Katherinehaven

In [ ]:
df = pd.read_csv('applicants.csv.csv')

In [ ]:
import pandas as pd

In [ ]:
# Add missing values
df.loc[[2, 7, 18, 24, 36, 48], "Email"] = None
df.loc[10, "Age"] = None

# Inconsistent formatting
df.loc[4, "City"] = " islamabad "
df.loc[9, "Name"] = "  Ayesha Malik  "
df.loc[25, "City"] = "LAHORE"
df.loc[33, "Email"] = " ali@example.com "

# Invalid emails
df.loc[12, "Email"] = "invalid-email"
df.loc[30, "Email"] = "abc@"
df.loc[45, "Email"] = "user@@gmail.com"

# Invalid ages
df.loc[14, "Age"] = -5
df.loc[28, "Age"] = 150
df.loc[39, "Age"] = "twenty-five"

# Duplicate rows
df.loc[15] = df.loc[0]
df.loc[40] = df.loc[10]

# Save messy dataset
df.to_csv("applicants.csv", index=False)
display(df)

/tmp/ipykernel_1660/189783241.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'twenty-five' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[39, "Age"] = "twenty-five"

,Applicant_ID,Name,Email,Age,City
0,1,Valerie Keith,zbeck@example.net,39.0,Wolfetown
1,2,Anthony Meyers,eddie62@example.net,22.0,Leeberg
2,3,Mark Valdez,None,37.0,New Stephenville
3,4,Mr. Jose Larson DDS,woodardnancy@example.net,27.0,Turnerbury
4,5,Andrew Hunter,brewerheidi@example.com,21.0,islamabad
5,6,Gary Rodriguez,yolandasandoval@example.com,24.0,Lake Julia
6,7,Robert Trevino,asanders@example.org,28.0,North Stephaniechester
7,8,Robert Moreno,None,40.0,West Meghan
8,9,Whitney Yates,navarropeter@example.net,21.0,Gomezfort
9,10,Ayesha Malik,john91@example.com,20.0,Erinmouth
10,11,Stephen Nguyen,usutton@example.net,NaN,North Rachael
11,12,Matthew Daniels MD,scohen@example.com,24.0,Lake Samuel
12,13,Sherri Evans,invalid-email,30.0,Hernandezmouth
13,14,Lee Higgins,andrew02@example.com,35.0,Dicksonfurt
14,15,Rhonda Hall,dustinnovak@example.org,-5.0,Port Robert
15,1,Valerie Keith,zbeck@example.net,39.0,Wolfetown
16,17,Aaron Nash,ruizjustin@example.org,28.0,Websterside
17,18,Michael Lambert,ssmith@example.org,21.0,Lake Amandaville
18,19,Brandon Page,None,36.0,Phillipshaven
19,20,Brittany Johnson,delacruzsusan@example.net,23.0,Hortonburgh
20,21,Michael Cooper,johnwaters@example.org,39.0,South Cheyenneville
21,22,Samantha Kelley,kristybrown@example.com,28.0,Williamshire
22,23,David Greene,nancydougherty@example.net,35.0,Michellebury
23,24,Patricia Woodard,higginstara@example.net,33.0,Millerstad
24,25,Lindsey Collins,None,29.0,South Robert
25,26,Mr. Jose Palmer,james57@example.org,31.0,LAHORE
26,27,Jennifer Morales,wolfkenneth@example.net,37.0,Michaelberg
27,28,Antonio Sparks,nphillips@example.net,31.0,Josephhaven
28,29,Joanna Michael,daltonspence@example.com,150.0,Collinsbury
29,30,Kaitlyn Goodwin,kimberlykelley@example.com,29.0,Port Ricardo
30,31,Brian Schaefer,abc@,29.0,Garrettton
31,32,Robert Lewis,brian48@example.net,20.0,Kirbyton
32,33,Amy Campbell,timothyscott@example.org,39.0,South Seanton
33,34,Mandy Garcia,ali@example.com,40.0,Nelsonfurt
34,35,Terry Rush,lesummer@example.com,27.0,Weissmouth
35,36,James Henson,hlloyd@example.net,29.0,South Lindsey
36,37,Gary Noble,None,22.0,Hallchester
37,38,Samuel Simpson,ryanperez@example.com,28.0,West Kevinstad
38,39,Kimberly Fernandez,richardnelson@example.com,28.0,Gomeztown
39,40,David Weber,thomasgregory@example.org,twenty-five,South Michaelton
40,11,Stephen Nguyen,usutton@example.net,NaN,North Rachael
41,42,Kayla Cook,fstokes@example.net,40.0,Christopherside
42,43,Shelly Watts,eford@example.net,38.0,Johntown
43,44,Allison Bell,webstertimothy@example.net,29.0,North Sharonland
44,45,Kelly Davis,jamie44@example.net,29.0,Kathrynstad
45,46,Robert Trujillo,user@@gmail.com,20.0,Lefurt
46,47,Teresa Beltran,larryhicks@example.com,30.0,South Jonathanmouth
47,48,James Baker,wperez@example.net,31.0,Zacharystad
48,49,Xavier Charles MD,None,30.0,West Janeburgh
49,50,Melanie Barnett,kimberly05@example.org,25.0,Thomasborough
50,51,Amanda Hernandez,larsonsamantha@example.org,30.0,New Justin
51,52,Steven Cervantes,bradleysantos@example.org,29.0,Lake Craig
52,53,Austin Roman,murrayjoyce@example.org,27.0,Villahaven
53,54,Kimberly Gallagher,westsean@example.org,33.0,Lake Seanmouth
54,55,Alexander Robinson,hbrown@example.net,29.0,North Julia
55,56,Tracy Morse,elizabethmack@example.com,22.0,South Aliciaburgh
56,57,Jordan Gill MD,krista84@example.net,20.0,Lake Christinamouth
57,58,Michael Floyd,ashley57@example.com,39.0,Dawnton
58,59,Margaret Oconnor,doylekaren@example.net,37.0,Danielton
59,60,Jacob Tran,chenrichard@example.com,37.0,Anneborough
60,61,Danielle Harris,dawsonveronica@example.com,25.0,East Traciside
61,62,Donald Rivas,christopher07@example.net,31.0,West Seth
62,63,Robert Moore,grantrice@example.org,35.0,Jonathanshire
63,64,Crystal Jensen,asmith@example.net,29.0,Port Colton
64,65,Daniel Williams,jonathan84@example.net,24.0,South Scottland
65,66,Nathan Stevens,michaellewis@example.net,20.0,Samanthaland
66,67,Nicholas Harding,tmarquez@example.org,31.0,Port Ann
67,68,Hannah Blair,tracy25@example.com,25.0,Port Rebeccastad
68,69,Warren Lee,christopher44@example.net,33.0,Melissabury
69,70,Krystal Mcbride,mcconnellmichelle@example.org,39.0,Port Jeffery
70,71,Eric Thomas,adamsaudrey@example.net,32.0,Mccarthyview
71,72,Theodore Burton,martinsteven@example.net,40.0,Amandaport
72,73,Matthew Summers,ujacobs@example.net,29.0,Lake Vincent
73,74,Margaret Gordon,kiddbrittany@example.org,29.0,West Troy
74,75,Steven Hughes,xpotts@example.net,35.0,East Loretta
75,76,Steven Hughes,ashley91@example.org,40.0,Cuevashaven
76,77,Angela Aguilar,robertcarrillo@example.net,40.0,Nathanberg
77,78,Samantha Brooks,stewartpaul@example.net,36.0,Lewishaven
78,79,Tiffany Stanley,powelljasmine@example.com,30.0,Huertafurt
79,80,Aaron Santiago,vlowe@example.org,31.0,Port Suzanne
80,81,Rachel Russell,jonesdeanna@example.com,33.0,Thomasville
81,82,Susan Mccall,justin33@example.net,24.0,Ericksonfort
82,83,Heather Parrish,nguyenmargaret@example.org,20.0,Travisbury
83,84,Joseph Barnes,rebecca15@example.org,38.0,Brownview
84,85,Randall Scott,michelle28@example.net,31.0,Anthonyfurt
85,86,William Park,ztucker@example.net,31.0,West Jillside
86,87,Amy Ellis,dorseyjustin@example.net,21.0,Port Stephen
87,88,Donna Estes,gregory00@example.org,24.0,Davismouth
88,89,Victoria Peck,philiphebert@example.com,26.0,North Haleystad
89,90,David Gonzales,michael46@example.org,25.0,Lake Karenfort
90,91,Julie Barber,mpotter@example.com,32.0,North Teresa
91,92,James Mitchell,bhunt@example.com,37.0,South Benjaminview
92,93,Jessica Guzman,kenneth37@example.org,38.0,Hamiltonborough
93,94,Pamela Shaw,joshuamiranda@example.net,33.0,East Chase
94,95,Joshua Kline,sarah13@example.net,39.0,Michelleside
95,96,Tiffany Johnson,tanyabarber@example.net,24.0,Lake Lisafort
96,97,Stephen Ward,bonillaconnie@example.com,32.0,Cherylmouth
97,98,John Hughes,greenkirsten@example.org,30.0,Marshmouth
98,99,Patricia Bates,kendraalexander@example.org,26.0,Michaelmouth
99,100,Andrew Brown,alexandratravis@example.com,34.0,West Richardtown

# New Section

In [ ]:
import pandas as pd
from faker import Faker
import random

fake = Faker()

data = []

for i in range(100):
    applicant = {
        "Applicant_ID": i + 1,
        "Name": fake.name(),
        "Email": fake.email(),
        "Age": random.randint(20, 40),
        "City": fake.city()
    }

    data.append(applicant)

df = pd.DataFrame(data)

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)

display(df)

,Applicant_ID,Name,Email,Age,City
0,1,Valerie Keith,zbeck@example.net,39,Wolfetown
1,2,Anthony Meyers,eddie62@example.net,22,Leeberg
2,3,Mark Valdez,brenda99@example.net,37,New Stephenville
3,4,Mr. Jose Larson DDS,woodardnancy@example.net,27,Turnerbury
4,5,Andrew Hunter,brewerheidi@example.com,21,Barrerabury
5,6,Gary Rodriguez,yolandasandoval@example.com,24,Lake Julia
6,7,Robert Trevino,asanders@example.org,28,North Stephaniechester
7,8,Robert Moreno,thomas51@example.com,40,West Meghan
8,9,Whitney Yates,navarropeter@example.net,21,Gomezfort
9,10,Nicole Obrien,john91@example.com,20,Erinmouth
10,11,Stephen Nguyen,usutton@example.net,22,North Rachael
11,12,Matthew Daniels MD,scohen@example.com,24,Lake Samuel
12,13,Sherri Evans,johnsonpatrick@example.com,30,Hernandezmouth
13,14,Lee Higgins,andrew02@example.com,35,Dicksonfurt
14,15,Rhonda Hall,dustinnovak@example.org,35,Port Robert
15,16,Heather Hernandez,usmith@example.com,28,Victorland
16,17,Aaron Nash,ruizjustin@example.org,28,Websterside
17,18,Michael Lambert,ssmith@example.org,21,Lake Amandaville
18,19,Brandon Page,barbara77@example.org,36,Phillipshaven
19,20,Brittany Johnson,delacruzsusan@example.net,23,Hortonburgh
20,21,Michael Cooper,johnwaters@example.org,39,South Cheyenneville
21,22,Samantha Kelley,kristybrown@example.com,28,Williamshire
22,23,David Greene,nancydougherty@example.net,35,Michellebury
23,24,Patricia Woodard,higginstara@example.net,33,Millerstad
24,25,Lindsey Collins,adamsalexis@example.org,29,South Robert
25,26,Mr. Jose Palmer,james57@example.org,31,Port Haileyfort
26,27,Jennifer Morales,wolfkenneth@example.net,37,Michaelberg
27,28,Antonio Sparks,nphillips@example.net,31,Josephhaven
28,29,Joanna Michael,daltonspence@example.com,38,Collinsbury
29,30,Kaitlyn Goodwin,kimberlykelley@example.com,29,Port Ricardo
30,31,Brian Schaefer,jimenezscott@example.com,29,Garrettton
31,32,Robert Lewis,brian48@example.net,20,Kirbyton
32,33,Amy Campbell,timothyscott@example.org,39,South Seanton
33,34,Mandy Garcia,ronaldkramer@example.net,40,Nelsonfurt
34,35,Terry Rush,lesummer@example.com,27,Weissmouth
35,36,James Henson,hlloyd@example.net,29,South Lindsey
36,37,Gary Noble,amberayala@example.com,22,Hallchester
37,38,Samuel Simpson,ryanperez@example.com,28,West Kevinstad
38,39,Kimberly Fernandez,richardnelson@example.com,28,Gomeztown
39,40,David Weber,thomasgregory@example.org,28,South Michaelton
40,41,John Rose,ashleywilliams@example.org,30,Garciaburgh
41,42,Kayla Cook,fstokes@example.net,40,Christopherside
42,43,Shelly Watts,eford@example.net,38,Johntown
43,44,Allison Bell,webstertimothy@example.net,29,North Sharonland
44,45,Kelly Davis,jamie44@example.net,29,Kathrynstad
45,46,Robert Trujillo,diazjohn@example.org,20,Lefurt
46,47,Teresa Beltran,larryhicks@example.com,30,South Jonathanmouth
47,48,James Baker,wperez@example.net,31,Zacharystad
48,49,Xavier Charles MD,amanda43@example.com,30,West Janeburgh
49,50,Melanie Barnett,kimberly05@example.org,25,Thomasborough
50,51,Amanda Hernandez,larsonsamantha@example.org,30,New Justin
51,52,Steven Cervantes,bradleysantos@example.org,29,Lake Craig
52,53,Austin Roman,murrayjoyce@example.org,27,Villahaven
53,54,Kimberly Gallagher,westsean@example.org,33,Lake Seanmouth
54,55,Alexander Robinson,hbrown@example.net,29,North Julia
55,56,Tracy Morse,elizabethmack@example.com,22,South Aliciaburgh
56,57,Jordan Gill MD,krista84@example.net,20,Lake Christinamouth
57,58,Michael Floyd,ashley57@example.com,39,Dawnton
58,59,Margaret Oconnor,doylekaren@example.net,37,Danielton
59,60,Jacob Tran,chenrichard@example.com,37,Anneborough
60,61,Danielle Harris,dawsonveronica@example.com,25,East Traciside
61,62,Donald Rivas,christopher07@example.net,31,West Seth
62,63,Robert Moore,grantrice@example.org,35,Jonathanshire
63,64,Crystal Jensen,asmith@example.net,29,Port Colton
64,65,Daniel Williams,jonathan84@example.net,24,South Scottland
65,66,Nathan Stevens,michaellewis@example.net,20,Samanthaland
66,67,Nicholas Harding,tmarquez@example.org,31,Port Ann
67,68,Hannah Blair,tracy25@example.com,25,Port Rebeccastad
68,69,Warren Lee,christopher44@example.net,33,Melissabury
69,70,Krystal Mcbride,mcconnellmichelle@example.org,39,Port Jeffery
70,71,Eric Thomas,adamsaudrey@example.net,32,Mccarthyview
71,72,Theodore Burton,martinsteven@example.net,40,Amandaport
72,73,Matthew Summers,ujacobs@example.net,29,Lake Vincent
73,74,Margaret Gordon,kiddbrittany@example.org,29,West Troy
74,75,Steven Hughes,xpotts@example.net,35,East Loretta
75,76,Steven Hughes,ashley91@example.org,40,Cuevashaven
76,77,Angela Aguilar,robertcarrillo@example.net,40,Nathanberg
77,78,Samantha Brooks,stewartpaul@example.net,36,Lewishaven
78,79,Tiffany Stanley,powelljasmine@example.com,30,Huertafurt
79,80,Aaron Santiago,vlowe@example.org,31,Port Suzanne
80,81,Rachel Russell,jonesdeanna@example.com,33,Thomasville
81,82,Susan Mccall,justin33@example.net,24,Ericksonfort
82,83,Heather Parrish,nguyenmargaret@example.org,20,Travisbury
83,84,Joseph Barnes,rebecca15@example.org,38,Brownview
84,85,Randall Scott,michelle28@example.net,31,Anthonyfurt
85,86,William Park,ztucker@example.net,31,West Jillside
86,87,Amy Ellis,dorseyjustin@example.net,21,Port Stephen
87,88,Donna Estes,gregory00@example.org,24,Davismouth
88,89,Victoria Peck,philiphebert@example.com,26,North Haleystad
89,90,David Gonzales,michael46@example.org,25,Lake Karenfort
90,91,Julie Barber,mpotter@example.com,32,North Teresa
91,92,James Mitchell,bhunt@example.com,37,South Benjaminview
92,93,Jessica Guzman,kenneth37@example.org,38,Hamiltonborough
93,94,Pamela Shaw,joshuamiranda@example.net,33,East Chase
94,95,Joshua Kline,sarah13@example.net,39,Michelleside
95,96,Tiffany Johnson,tanyabarber@example.net,24,Lake Lisafort
96,97,Stephen Ward,bonillaconnie@example.com,32,Cherylmouth
97,98,John Hughes,greenkirsten@example.org,30,Marshmouth
98,99,Patricia Bates,kendraalexander@example.org,26,Michaelmouth
99,100,Andrew Brown,alexandratravis@example.com,34,West Richardtown

In [ ]:
from faker import Faker
fake = Faker()

print(fake.name())
print(fake.email())

Amber Freeman
williamconner@example.com

In [ ]:
!pip install Faker

Requirement already satisfied: Faker in /usr/local/lib/python3.13/dist-packages (40.43.0)

In [ ]:
import pandas as pd

# Week 1: Data Cleaning & Exploration Report
**Name**: Hafza Nazar